---
verbosity:   2         # 0 (silent) to 5 (very chatty)
debug: false
stateFile:  "./stateFile"
cooling:
    useCooler:        false     # Use camera's cooler?
    # The following used only if useCooler=true
    coolTo:           -10.0     # Target temp
    coolStartTol:     2.0       # Get this close before starting
    coolWaitMinutes:  30        # Wait this long then give up
    startPollSeconds: 10        # How often to poll temp when starting
    abortOnCooling:   true      # Abort collection if camera temp rises    
    coolAbortTol:     2.0       # Abort if temp deviates this much
    offAtEnd:         true      # Turn cooler off at end of capture?
start:
    delay:  false      # false=start now;  true=start later
    day:    today      # Ignored if delay=false         
    time:   14:04      # Ignored if daley=false
server:
   address: "localhost"       # localhost, domain, or IP address
   port:    3040              # Port number of at that address
biasframes:     # List of strings "number,binning"
    - "1,1"
    - "1,3"
    - "1,2"
darkframes:     # List of strings "number,exposure,binning"
    - "1,6,1"
    - "1,3,1"
    - "1,8,2"




