---
verbosity:    2              # default 1
debug: false
stateFile:  "./stateFile.state"
cooling:
    useCooler:        false
    coolTo:           -10.0
    coolStartTol:     2.0
    coolWaitMinutes:  30
    abortOnCooling:   true
    coolAbortTol:     2.0
    offAtEnd:         true
start:
    delay:  false
    day: today
    time: 14:04
server:
   address: "localhost"       # default localhost
   port:    3040              # default 3040
biasframes:
   -  biasset:
        frames:  8
        binning: 1
   -  biasset:
        frames:  8
        binning: 2
darkframes:
  -  darkset:
       frames:  3
       seconds: 10
       binning: 1
  -  darkset:
       frames:  3
       seconds: 15
       binning: 2
  -  darkset:
       frames:  3
       seconds: 20
       binning: 1
